# Generated by Django 4.2.6 on 2024-07-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='CustomUser',
        ),
    ]
