# Generated by Django 4.2.6 on 2024-07-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_rename_user_wishlist_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='CustomUser',
            new_name='Users',
        ),
    ]
