# Generated by Django 4.2.3 on 2024-07-18 22:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import groupbuys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('end_date', models.DateTimeField(default=groupbuys.models.one_week_from_now)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('min_quantity', models.PositiveIntegerField(default=0)),
                ('max_quantity', models.PositiveIntegerField(default=0)),
                ('target_quantity', models.PositiveIntegerField(default=0)),
                ('current_quantity', models.PositiveBigIntegerField(default=0)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupbuys.groupbuy')),
            ],
        ),
    ]
