# Generated by Django 4.2.3 on 2024-07-18 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupbuys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='group',
            field=models.ManyToManyField(related_name='groupbuys_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='users',
            field=models.ManyToManyField(related_name='groupbuys_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
