# Generated by Django 4.2.6 on 2024-07-03 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('groupbuys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
