# Generated by Django 4.2.3 on 2024-07-26 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupbuys', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupbuy',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupbuy',
            name='product',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='groupbuy',
            name='current_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupbuy',
            name='users',
            field=models.ManyToManyField(related_name='groupbuys', to=settings.AUTH_USER_MODEL),
        ),
    ]
