# Generated by Django 4.2.3 on 2024-07-28 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupbuys', '0003_remove_groupbuy_group_remove_groupbuy_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBuyParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
        migrations.AddField(
            model_name='groupbuyparticipation',
            name='group_buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupbuys.groupbuy'),
        ),
        migrations.AddField(
            model_name='groupbuyparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
