# Generated by Django 4.2.6 on 2024-07-04 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import groupbuys.models  # Import the models to access the one_week_from_now function

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupbuys', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuy',
            name='current_quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='end_date',
            field=models.DateTimeField(default=groupbuys.models.one_week_from_now),
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='max_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='min_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupbuy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupbuys.groupbuy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
