# Generated by Django 4.2.6 on 2024-07-04 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groupbuys', '0004_groupbuy_current_quantity_groupbuy_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbuy',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
