# Generated by Django 4.2.6 on 2024-07-04 14:03
from django.utils.timezone import timedelta
from django.db import migrations, models
import groupbuys.models


class Migration(migrations.Migration):

    dependencies = [
        ('groupbuys', '0005_alter_groupbuy_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbuy',
            name='end_date',
            field=models.DateTimeField(default=groupbuys.models.one_week_from_now),
        ),
    ]
