# Generated by Django 4.2.6 on 2024-07-04 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupbuys', '0006_alter_groupbuy_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuy',
            name='discount_percentage',
              field=models.DecimalField(max_digits=5, decimal_places=2, default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='target_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
