# Generated by Django 4.2.6 on 2024-07-07 13:21

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupbuys', '0007_groupbuy_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuy',
            name='group',
            field=models.ManyToManyField(related_name='groupbuys_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='participation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupbuy',
            name='users',
            field=models.ManyToManyField(related_name='groupbuys_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
